version: "3"
services:
  
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=timesheet-spring
      - MYSQL_PASSWORD=root
    ports:
      - 3309:3309
  
  Timesheet:
    container_name: timesheet_devops
    ports:
      - 8082:8082
    environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/timeSheetDevOps?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
     - SPRING_DATASOURCE_USERNAME=root
     - DATABASE_USER=root
     - SPRING_DATASOURCE_PASSWORD=root
     - DATABASE_NAME=timeSheetDevOps
     - DATABASE_PORT=3306
    hostname: timesheet_devops
    image: "ouss97/timesheetrepo"
    depends_on:
      - mysql