version: '3.3'

services:
    #service 1: definition of mysql database
    db:
      image: mysql:latest
      container_name: mysql-db  
      environment:
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "3309:3308"
      restart: always

    #service 2: definition of phpMyAdmin
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: my-php-myadmin
      ports:
        - "8082:80"
      restart: always

      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: 



    #service 3: definition of your spring-boot app 
    timesheet_devops:                        #it is just a name, which will be used only in this file.
      image: timesheet_devops.jar               #name of the image after dockerfile executes
      container_name: timesheet_devops.jar #name of the container created from docker image
      build: .
      ports:
        - "8084:8081"                       #docker containter port with your os port
      restart: always

      depends_on:                           #define dependencies of this app
        - db                                #dependency name (which is defined with this name 'db' in this file earlier)
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3308/timeSheetDevOps?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root