FROM openjdk:11-jre-alpine
EXPOSE 8081
ADD target/Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.1.jar Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.1.jar
ENTRYPOINT ["java", "-jar", "/Timesheet-spring-boot-core-data-jpa-mvc-REST-1-1.1.jar"]